# Generated by Django 5.2.4 on 2025-08-24 05:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_notifications', models.BooleanField(default=True, help_text='Receive email notifications')),
                ('push_notifications', models.BooleanField(default=True, help_text='Receive push notifications')),
                ('profile_visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('friends', 'Friends Only')], default='public', max_length=20)),
                ('show_online_status', models.BooleanField(default=True)),
                ('show_activity', models.BooleanField(default=True)),
                ('allow_messages', models.CharField(choices=[('everyone', 'Everyone'), ('friends', 'Friends Only'), ('none', 'No One')], default='everyone', max_length=20)),
                ('auto_save', models.BooleanField(default=True, help_text='Auto-save answers during exam')),
                ('auto_save_interval', models.IntegerField(default=30, help_text='Auto-save interval in seconds')),
                ('show_timer', models.BooleanField(default=True, help_text='Show timer during exam')),
                ('confirm_navigation', models.BooleanField(default=True, help_text='Confirm before navigating away')),
                ('keyboard_shortcuts', models.BooleanField(default=True, help_text='Enable keyboard shortcuts')),
                ('show_question_palette', models.BooleanField(default=True, help_text='Show question navigation palette')),
                ('enable_calculator', models.BooleanField(default=True, help_text='Enable calculator in exams')),
                ('enable_rough_sheet', models.BooleanField(default=True, help_text='Enable rough sheet/notepad')),
                ('mark_review_enabled', models.BooleanField(default=True, help_text='Enable mark for review feature')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto (System)')], default='light', max_length=10)),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ta', 'Tamil'), ('te', 'Telugu'), ('mr', 'Marathi'), ('gu', 'Gujarati'), ('bn', 'Bengali'), ('kn', 'Kannada'), ('ml', 'Malayalam'), ('pa', 'Punjabi')], default='en', max_length=5)),
                ('timezone', models.CharField(choices=[('Asia/Kolkata', 'India Standard Time (IST)'), ('Asia/Dubai', 'Gulf Standard Time (GST)'), ('Asia/Singapore', 'Singapore Time (SGT)'), ('Europe/London', 'British Time (GMT/BST)'), ('America/New_York', 'Eastern Time (EST/EDT)'), ('America/Los_Angeles', 'Pacific Time (PST/PDT)')], default='Asia/Kolkata', max_length=50)),
                ('date_format', models.CharField(choices=[('DD/MM/YYYY', 'DD/MM/YYYY'), ('MM/DD/YYYY', 'MM/DD/YYYY'), ('YYYY-MM-DD', 'YYYY-MM-DD'), ('DD-MM-YYYY', 'DD-MM-YYYY')], default='DD/MM/YYYY', max_length=20)),
                ('time_format_24h', models.BooleanField(default=False, help_text='Use 24-hour time format')),
                ('results_per_page', models.IntegerField(choices=[(10, '10'), (25, '25'), (50, '50'), (100, '100')], default=10)),
                ('default_view', models.CharField(choices=[('grid', 'Grid View'), ('list', 'List View'), ('compact', 'Compact View')], default='grid', max_length=20)),
                ('sidebar_collapsed', models.BooleanField(default=False)),
                ('show_recent_activity', models.BooleanField(default=True)),
                ('high_contrast', models.BooleanField(default=False, help_text='Enable high contrast mode')),
                ('font_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('extra_large', 'Extra Large')], default='medium', max_length=20)),
                ('screen_reader_mode', models.BooleanField(default=False, help_text='Optimize for screen readers')),
                ('reduce_animations', models.BooleanField(default=False, help_text='Reduce UI animations')),
                ('notification_settings', models.JSONField(blank=True, default=dict, help_text='Detailed notification preferences')),
                ('custom_settings', models.JSONField(blank=True, default=dict, help_text='Additional custom settings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Preference',
                'verbose_name_plural': 'User Preferences',
                'db_table': 'user_preferences',
            },
        ),
    ]
