# Generated by create_data_migration.py on 2025-10-16 01:13:05.693912

from django.db import migrations
from django.core.management import call_command
import os

def load_fixture_data(apps, schema_editor):
    """Load data from fixtures in correct order"""
    fixture_dir = os.path.join(os.path.dirname(__file__), '..', '..', 'fixtures')

    # Order matters - respects foreign key dependencies
    fixture_order = [
        'users.json',
        'exams.json',
        'questions.json',
        'knowledge.json',
        'payments.json',
        'analytics.json',
    ]

    for fixture_file in fixture_order:
        fixture_path = os.path.join(fixture_dir, fixture_file)
        if os.path.exists(fixture_path):
            print(f"Loading {fixture_file}...")
            call_command('loaddata', fixture_path, verbosity=1)
        else:
            print(f"Skipping {fixture_file} (not found)")

def reverse_data(apps, schema_editor):
    """Reverse migration - delete imported data"""
    # This is optional - be careful with this!
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userpreferences'),
    ]

    operations = [
        migrations.RunPython(load_fixture_data, reverse_data),
    ]
