# Generated by Django 5.2.4 on 2025-08-24 06:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicImportTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('template_type', models.CharField(choices=[('full', 'Complete Topic Hierarchy'), ('selective', 'Selected Topics Only'), ('condensed', 'Condensed Version'), ('extended', 'Extended with Prerequisites')], max_length=20)),
                ('include_prerequisites', models.BooleanField(default=False)),
                ('include_subtopics', models.BooleanField(default=True)),
                ('max_depth_level', models.IntegerField(default=5, help_text='Maximum depth to import')),
                ('filter_by_difficulty', models.JSONField(blank=True, default=list, help_text='Difficulty levels to include')),
                ('usage_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('root_topics', models.ManyToManyField(blank=True, related_name='import_templates', to='knowledge.globaltopic')),
                ('source_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_templates', to='knowledge.globalsubject')),
            ],
            options={
                'db_table': 'topic_import_templates',
                'ordering': ['-usage_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SyllabusTopicMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('syllabus_id', models.UUIDField()),
                ('syllabus_node_id', models.UUIDField()),
                ('custom_title', models.CharField(blank=True, help_text='Override title if needed', max_length=255)),
                ('custom_description', models.TextField(blank=True, help_text='Exam-specific description')),
                ('custom_weightage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('custom_estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_mandatory', models.BooleanField(default=True, help_text='Required for this exam')),
                ('is_modified', models.BooleanField(default=False, help_text='Has exam-specific modifications')),
                ('modification_notes', models.TextField(blank=True, help_text='Notes about modifications made')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('global_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_mappings', to='knowledge.globaltopic')),
            ],
            options={
                'db_table': 'syllabus_topic_mappings',
                'indexes': [models.Index(fields=['syllabus_id', 'global_topic'], name='syllabus_to_syllabu_61cfef_idx'), models.Index(fields=['is_mandatory', 'is_modified'], name='syllabus_to_is_mand_7f460a_idx')],
                'unique_together': {('syllabus_node_id', 'global_topic')},
            },
        ),
    ]
