# Generated by Django 5.2.4 on 2025-07-29 08:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('times_appeared', models.IntegerField(default=0)),
                ('times_answered', models.IntegerField(default=0)),
                ('times_correct', models.IntegerField(default=0)),
                ('average_time_spent', models.IntegerField(default=0)),
                ('difficulty_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'question_analytics',
            },
        ),
        migrations.CreateModel(
            name='TestAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_attempts', models.IntegerField(default=0)),
                ('total_completions', models.IntegerField(default=0)),
                ('average_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('average_completion_time', models.IntegerField(default=0)),
                ('pass_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('difficulty_distribution', models.JSONField(default=dict)),
                ('question_performance', models.JSONField(default=list)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'test_analytics',
            },
        ),
        migrations.CreateModel(
            name='UserAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_tests_taken', models.IntegerField(default=0)),
                ('total_tests_passed', models.IntegerField(default=0)),
                ('average_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_time_spent_minutes', models.IntegerField(default=0)),
                ('strongest_topics', models.JSONField(default=list)),
                ('weakest_topics', models.JSONField(default=list)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_analytics',
            },
        ),
    ]
