# Generated by Django 5.2.4 on 2025-07-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_extractor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingjob',
            name='current_step_display',
            field=models.CharField(blank=True, help_text='Human-readable current step description', max_length=100),
        ),
    ]
