# Generated by Django 5.2.4 on 2025-07-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_extractor', '0002_add_current_step_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedquestion',
            name='is_rejected',
            field=models.BooleanField(default=False, help_text='True if manually rejected during review'),
        ),
        migrations.AddField(
            model_name='extractedquestion',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata from processing and review'),
        ),
    ]
