# Generated by Django 5.2.4 on 2025-07-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_extractor', '0003_extractedquestion_is_rejected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingstatistics',
            name='layout_analysis_used',
            field=models.BooleanField(default=False, help_text='Whether layout analysis was used'),
        ),
        migrations.AddField(
            model_name='processingstatistics',
            name='low_confidence_questions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processingstatistics',
            name='medium_confidence_questions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processingstatistics',
            name='ocr_used',
            field=models.BooleanField(default=False, help_text='Whether OCR was used'),
        ),
        migrations.AddField(
            model_name='processingstatistics',
            name='processing_method',
            field=models.CharField(default='standard', help_text='Method used for processing', max_length=50),
        ),
    ]
