# Generated by Django 5.2.4 on 2025-07-31 17:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_extractor', '0005_regionreviewsession_regioncorrection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageReviewStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('no_questions', 'No Questions'), ('skipped', 'Skipped'), ('error', 'Error')], default='pending', max_length=20)),
                ('questions_found', models.PositiveIntegerField(default=0)),
                ('questions_extracted', models.PositiveIntegerField(default=0)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_statuses', to='pdf_extractor.pdfdocument')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'page_review_status',
                'ordering': ['page_number'],
                'unique_together': {('pdf_document', 'page_number')},
            },
        ),
    ]
