# Generated by Django 5.2.4 on 2025-07-31 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_extractor', '0006_add_page_review_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagereviewstatus',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('no_questions', 'No Questions'), ('pending_unsupported', 'Pending - Unsupported Type'), ('skipped', 'Skipped'), ('error', 'Error')], default='pending', max_length=20),
        ),
    ]
