# Generated by Django 5.2.4 on 2025-07-31 18:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_extractor', '0007_update_page_status_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedRegion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_number', models.PositiveIntegerField()),
                ('coordinates', models.JSONField(help_text='Region coordinates {x, y, width, height}')),
                ('region_type', models.CharField(choices=[('question', 'Question'), ('answer_options', 'Answer Options'), ('passage', 'Passage/Context'), ('diagram', 'Diagram'), ('table', 'Table'), ('mixed', 'Mixed Content'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('extracted_text', models.TextField(blank=True, help_text='OCR extracted text from region')),
                ('confidence_score', models.FloatField(default=0.0, help_text='Detection/OCR confidence 0-1')),
                ('status', models.CharField(choices=[('detected', 'Detected'), ('completed', 'Questions Extracted'), ('unsupported', 'Unsupported Type'), ('no_questions', 'No Questions'), ('error', 'Processing Error')], default='detected', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='User notes about this region')),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('extracted_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_regions', to='pdf_extractor.extractedquestion')),
                ('pdf_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_regions', to='pdf_extractor.pdfdocument')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_regions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saved_regions',
                'ordering': ['page_number', 'coordinates'],
                'indexes': [models.Index(fields=['pdf_document', 'page_number'], name='saved_regio_pdf_doc_d112d1_idx'), models.Index(fields=['status'], name='saved_regio_status_f4df95_idx'), models.Index(fields=['region_type'], name='saved_regio_region__9dea31_idx')],
            },
        ),
    ]
