# Generated by Django 5.2.4 on 2025-08-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_extractor', '0009_add_document_metadata_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfdocument',
            name='source_type',
            field=models.CharField(blank=True, choices=[('previous_year', 'Previous Year Paper'), ('mock_test', 'Mock Test'), ('sample_paper', 'Sample Paper'), ('practice_set', 'Practice Set'), ('study_material', 'Study Material'), ('question_bank', 'Question Bank'), ('textbook', 'Textbook'), ('notes', 'Study Notes'), ('reference_book', 'Reference Book'), ('online_resource', 'Online Resource'), ('coaching_material', 'Coaching Material'), ('other', 'Other')], help_text='Type of document source', max_length=50),
        ),
    ]
